### ISSUE TITLE
Error message when trying to send text message

### ISSUE THREAD

**Issue by hui99995** [Xcreen/RestSMS#3] opened 2022-05-04 07:58 UTC
root@HK3:~# curl -X POST http://172.29.29.4:8080/send -H 'Cache-Control: no-cache' -H 'Content-Type: application/x-www-form-urlencoded' -d 'message=Hello%20World&phoneno=%2B8610001'
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 500 </title>
</head>
<body>
<h2>HTTP ERROR: 500</h2>
<p>Problem accessing /send. Reason:
<pre>    java.lang.NullPointerException: Attempt to invoke virtual method &apos;void android.telephony.SmsManager.sendTextMessage(java.lang.String, java.lang.String, java.lang.String, android.app.PendingIntent, android.app.PendingIntent)&apos; on a null object reference</pre></p>
<hr /><i><small>Powered by Jetty://</small></i>
</body>
</html>

**Comment by Xcreen** [comment] 2022-05-19 08:07
Sorry for the late response, which android device and version you are using?
It looks like it cant initialize the SmsManager. There was a change in version 2.2.0, can you test with 2.1.0 and check if that works?

**Comment by hui99995** [comment] 2022-05-23 03:42
Thanks for changing the version

**Comment by Xcreen** [comment] 2022-05-23 16:18
I was able to reproduce the problem on a android 6 device.  
It should now be fixed with version 2.2.1.

**Closed by Xcreen** 2022-05-23 16:18 UTC
